# Generated by Django 5.0.4 on 2024-05-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_vehiculos', models.IntegerField(default=0)),
                ('ultimo_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Deteccion',
        ),
    ]
